version: "3.7"
services:
  backupsystem:
    image: kaiede/minecraft-bedrock-backup
    restart: unless-stopped
    container_name: backupsystem
    depends_on:
      - "minecraft-survival"
      - "minecraft-creative"
      - "minecraft-nicks"
    environment:
      TZ: "America/Detroit"
    stdin_open: true
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - backupsystem:/backups
      - minecraft-survival:/minecraft-survival
      - minecraft-creative:/minecraft-creative
      - minecraft-nicks:/minecraft-nicks
    labels:
      - backupsystem=true

  manymine:
    image: illiteratealliterator/manymine
    restart: unless-stopped
    container_name: manymine
    ports:
      - '60600:19132/udp'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  webhook:
    image: ghcr.io/edward3h/mc-webhook:0.4
    restart: "unless-stopped"
    container_name: webhook
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes/minecraft_webhook/_data/config.yml:/config.yml
        
  messages:
    image: eclipse-mosquitto:2
    restart: "unless-stopped"
    container_name: messages
    volumes:
      - mosquitto-config:/mosquitto
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log

  map_server:
    image: halverneus/static-file-server:v1.8.5
    restart: "unless-stopped"
    container_name: mapserver
    volumes:
      - web:/web
    ports:
      - "8080:8080"
      
  map_builder:
    image: ghcr.io/edward3h/bedrock-viz-from-backups:v0.2
    restart: "unless-stopped"
    container_name: mapbuilder
    depends_on:
      - messages
    volumes:
      - backupsystem:/backups
      - /tmp:/data
      - web:/web
    environment:
      - MQTT_SERVER_HOST=messages
      - MQTT_SUBSCRIBE_TOPIC=mc-webhook
      - MQTT_PUBLISH_TOPIC=mc-maps
      - WEB_HOST_TARGET=/web
    
  minecraft-survival:
    image: itzg/minecraft-bedrock-server
    restart: unless-stopped
    container_name: minecraft-survival
    environment:
      EULA: "TRUE"
      SERVER_NAME: "minecraft-survival"
      GAMEMODE: "survival"
      DIFFICULTY: "normal"
      LEVEL_NAME: "minecraft-survival"
      MAX_PLAYERS: 10
    volumes:
      - minecraft-survival:/data
    stdin_open: true
    tty: true
    ports:
      - '60601:19132/udp'
    labels:
      - manymine.enable=true
      - minecraft-survival=true

  minecraft-creative:
    image: itzg/minecraft-bedrock-server
    restart: unless-stopped
    container_name: minecraft-creative
    environment:
      EULA: "TRUE"
      SERVER_NAME: "minecraft-creative"
      GAMEMODE: "creative"
      DIFFICULTY: "normal"
      LEVEL_NAME: "minecraft-creative"
      MAX_PLAYERS: 10
    volumes:
      - minecraft-creative:/data
    stdin_open: true
    tty: true
    ports:
      - '60602:19132/udp'
    labels:
      - manymine.enable=true
      - minecraft-creative=true
      
  minecraft-nicks:
    image: itzg/minecraft-bedrock-server
    restart: unless-stopped
    container_name: minecraft-nicks
    environment:
      EULA: "TRUE"
      SERVER_NAME: "minecraft-nicks"
      GAMEMODE: "survival"
      DIFFICULTY: "normal"
      LEVEL_NAME: "minecraft-nicks"
      MAX_PLAYERS: 10
    volumes:
      - minecraft-nicks:/data
    stdin_open: true
    tty: true
    ports:
      - '60603:19132/udp'
    labels:
      - manymine.enable=true
      - minecraft-nicks=true
      
volumes:
  minecraft-survival:
  minecraft-creative:
  minecraft-nicks:
  backupsystem:
  webhook:
  mosquitto-data:
  mosquitto-logs:  
  mosquitto-config:
  web:
  
